### Introduction To Pandas Module
Here, we are learning data analysis. Pandas is a software library written for the Python programming language that helps with data manipulation and analysis. It offers various data structures which help in the manipulation of data. <br>
One of the data structures used is DataFrame.<br>
DataFrame is used as a way to store data in a rectangular grid.<br>
Similar to how data is stored in Microsoft Excel.
### Installation
We can easily install this library using the terminal. Follow the steps given below to install Pandas:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install pandas with the help of pip easily. Head over to the directory where you want to install the pandas and fire the below command:<br>
__pip install pandas__<br>
This is very simple to install.

In [ ]:
# !pip install pandas

### Other way to install
If the above steps do not work for you, here is another way to install:<br>
Step 1: Go to your browser. Search for __python unofficial binaries__, or click <br>
https://www.lfd.uci.edu/~gohlke/pythonlibs/<br> 
and you will be redirected to the binary page.<br>
Step 2: To download the library, search for pandas – Ctrl + F will help you. Download pandas library based on your python version. <br>
Step 3: After the installation, head over to the directory where you've downloaded the pandas. <br>
Step 4: Right-click to open Windows PowerShell. Pip can help us with the installation. Just go to that location in your terminal and run the following command: <br>
__pip install pandas__ <br>
Complete this command by the TAB button so that the location of your folder is mentioned.

### import pandas
Once Pandas is installed, import it in your applications by adding the import keyword:<br>
__import pandas as pd__<br>
Now Pandas is imported and ready to use.

In [3]:
import pandas

In [4]:
dict1 = {
    'Name': ["Muhammad Mubeen", "Nadeem Khan", "Muhammad ahmad", "Nasir Khan","Shah Fahad"],
    'Marks': [90, 66, 79, 55, 34],
    'Class':["4st Year", "1nd Year", "5st Year", "6rd Year", "7nd Year"]
}

In [6]:
df = pandas.DataFrame(dict1)

In [7]:
df = pandas.DataFrame(dict1)

In [8]:
df

              Name  Marks     Class
0  Muhammad Mubeen     90  4st Year
1      Nadeem Khan     66  1nd Year
2   Muhammad ahmad     79  5st Year
3       Nasir Khan     55  6rd Year
4       Shah Fahad     34  7nd Year

### Pandas as pd
Pandas is usually imported under the pd alias.
#### alias: 
In Python alias are an alternate name for referring to the same thing.<br>
Create an alias with the as keyword while importing:<br>
__import pandas as pd__<br>
Now the Pandas package can be referred to as pd instead of pandas.

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(dict1)

In [11]:
df

              Name  Marks     Class
0  Muhammad Mubeen     90  4st Year
1      Nadeem Khan     66  1nd Year
2   Muhammad ahmad     79  5st Year
3       Nasir Khan     55  6rd Year
4       Shah Fahad     34  7nd Year

### Checking Pandas Version
The version string is stored under __version__ attribute.

In [12]:
pd.__version__

'2.3.3'

## Import to CSV

In [13]:
df.to_csv('pythonMonday.csv')

## Remove Index

In [14]:
df.to_csv('pythonMondayRemoveIndex.csv', index=False)

## Show some rows from the Start

In [15]:
df.head()

              Name  Marks     Class
0  Muhammad Mubeen     90  4st Year
1      Nadeem Khan     66  1nd Year
2   Muhammad ahmad     79  5st Year
3       Nasir Khan     55  6rd Year
4       Shah Fahad     34  7nd Year

In [16]:
df.head()

              Name  Marks     Class
0  Muhammad Mubeen     90  4st Year
1      Nadeem Khan     66  1nd Year
2   Muhammad ahmad     79  5st Year
3       Nasir Khan     55  6rd Year
4       Shah Fahad     34  7nd Year

In [17]:
df.tail(3)

             Name  Marks     Class
2  Muhammad ahmad     79  5st Year
3      Nasir Khan     55  6rd Year
4      Shah Fahad     34  7nd Year

In [18]:
df.tail()

              Name  Marks     Class
0  Muhammad Mubeen     90  4st Year
1      Nadeem Khan     66  1nd Year
2   Muhammad ahmad     79  5st Year
3       Nasir Khan     55  6rd Year
4       Shah Fahad     34  7nd Year

In [19]:
df.describe()

           Marks
count   5.000000
mean   64.800000
std    21.695622
min    34.000000
25%    55.000000
50%    66.000000
75%    79.000000
max    90.000000

In [72]:
classData= pd.read_csv("dataset.csv")

EmptyDataError: No columns to parse from file

In [ ]:
classData

            name    gpa class
0  ibraheem khan   3.94    3rd
1     tayyab khan  3.45    4th
2      abbas khan  2.90    5th
3      ayub khan   3.84    6th
4    mobeen khan   3.20    7th

In [ ]:
classData.drop(0, axis=0)

          name    gpa class
1   tayyab khan  3.45    4th
2    abbas khan  2.90    5th
3    ayub khan   3.84    6th
4  mobeen khan   3.20    7th

In [ ]:
classData

In [ ]:
classData['gpa']

First     90.00
Second     3.45
Third      2.90
Fourth     3.84
Fifth      5.00
Name: gpa, dtype: float64

In [ ]:
classData['class']

KeyError: 'class'

In [ ]:
classData['class ']

First     3rd
Second    4th
Third     5th
Fourth    6th
Fifth     7th
Name: class , dtype: object

In [ ]:
classData['name']

KeyError: 'name'

In [21]:
classData['name ']

NameError: name 'classData' is not defined

In [22]:
type(classData['name '])

NameError: name 'classData' is not defined

In [23]:
classData['gpa']

NameError: name 'classData' is not defined

In [24]:
classData['gpa'][0]

NameError: name 'classData' is not defined

In [25]:
classData['gpa'][0]=90

NameError: name 'classData' is not defined

In [26]:
classData

NameError: name 'classData' is not defined

In [27]:
classData['gpa'][4]

NameError: name 'classData' is not defined

In [28]:
classData['gpa'][4]=5

NameError: name 'classData' is not defined

In [29]:
classData["class "][4]="Second Year"

NameError: name 'classData' is not defined

In [ ]:
classData

                 name     gpa       class
First   ibraheem khan   90.00          3rd
Second     tayyab khan   3.45          4th
Third       abbas khan   2.90          5th
Fourth      ayub khan    3.84          6th
Fifth     mobeen khan    5.00  Second Year

In [ ]:
classData["name "][4]

'mobeen khan '

In [30]:
classData

NameError: name 'classData' is not defined

In [31]:
classData.to_csv('pythonMondayNew.csv')

NameError: name 'classData' is not defined

In [ ]:
classData.to_csv('pythonMondayNewRemoveIndex.csv', index=False)

## Create Labels
With the index argument, you can name your own labels.

In [32]:
classData.index = ["First","Second", "Third", "Fourth", "Fifth"]

NameError: name 'classData' is not defined

In [ ]:
classData

                 name     gpa class
First   ibraheem khan   90.00    3rd
Second     tayyab khan   3.45    4th
Third       abbas khan   2.90    5th
Fourth      ayub khan    3.84    6th
Fifth     mobeen khan    5.00    7th

In [33]:
classData["name"]["Fifth"]

NameError: name 'classData' is not defined

## Pandas 
Pandas is an open source data analysis library written in Python.<br>
It uses the power and speed of numpy to make data analysis and preprocessing easy for data scientists.<br>
__Pandas__ is used to analyze data.<br>
Python data analysis using pandas is a great start to Exploratory Data Analysis (EDA) for a data scientist.

## Pandas Data Structure
Panda has two types of Data Structure:<br> 
    a) Series<br>
    b) Dataframe
### Series
It is a one dimentional array with indexes. It stores a single column or row of data in a Dataframe.<br>
It is a one dimensional array capable of holding any type of data.
### Dataframe
It is a tabular spreadsheet like structure representing rows each of which contains one or more columns.<br>
It is a multi dimensional array capable of holding any type of data.<br>
__Series__ is like a column, a __DataFrame__ is the whole table.

In [ ]:
classData['gpa']

First     90.00
Second     3.45
Third      2.90
Fourth     3.84
Fifth      5.00
Name: gpa, dtype: float64

In [ ]:
 type(classData['gpa'])

pandas.core.series.Series

In [34]:
classData

NameError: name 'classData' is not defined

In [ ]:
type(classData)

pandas.core.frame.DataFrame

In [35]:
import numpy as np

In [36]:
series1= pd.Series(np.random.rand())

In [37]:
series1

0    0.577249
dtype: float64

In [38]:
series1= pd.Series(np.random.rand(30))

In [39]:
series1

0     0.574846
1     0.816840
2     0.974869
3     0.253980
4     0.426836
5     0.094238
6     0.597992
7     0.965797
8     0.913048
9     0.990587
10    0.239949
11    0.803658
12    0.970661
13    0.521811
14    0.716959
15    0.709608
16    0.674598
17    0.197458
18    0.500571
19    0.416999
20    0.582313
21    0.670356
22    0.603592
23    0.931337
24    0.400930
25    0.264810
26    0.736437
27    0.127053
28    0.562401
29    0.583237
dtype: float64

In [40]:
type(series1)

pandas.core.series.Series

In [41]:
newDf = pd.DataFrame(np.random.rand(330,5))
# newDf = pd.DataFrame(np.random.rand(330,5), index=np.arange(330))

In [42]:
type(newDf)

pandas.core.frame.DataFrame

In [43]:
newDf

            0         1         2         3         4
0    0.985387  0.577195  0.100032  0.632805  0.258135
1    0.716267  0.861450  0.982896  0.193007  0.908535
2    0.515366  0.942627  0.583046  0.299769  0.535384
3    0.175034  0.030987  0.642900  0.135789  0.606995
4    0.439564  0.023421  0.172769  0.969795  0.147122
..        ...       ...       ...       ...       ...
325  0.284240  0.336885  0.539418  0.405030  0.883733
326  0.537784  0.311931  0.704493  0.643169  0.119080
327  0.931486  0.743379  0.156919  0.945241  0.419434
328  0.286289  0.351732  0.458231  0.810107  0.389686
329  0.678228  0.167879  0.798366  0.369167  0.867209

[330 rows x 5 columns]

In [44]:
newDf.head(2)

          0         1         2         3         4
0  0.985387  0.577195  0.100032  0.632805  0.258135
1  0.716267  0.861450  0.982896  0.193007  0.908535

In [45]:
newDf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [46]:
newDf.tail(2)

            0         1         2         3         4
328  0.286289  0.351732  0.458231  0.810107  0.389686
329  0.678228  0.167879  0.798366  0.369167  0.867209

In [47]:
newDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       330 non-null    float64
 1   1       330 non-null    float64
 2   2       330 non-null    float64
 3   3       330 non-null    float64
 4   4       330 non-null    float64
dtypes: float64(5)
memory usage: 13.0 KB

In [48]:
newDf.describe()

                0           1           2           3           4
count  330.000000  330.000000  330.000000  330.000000  330.000000
mean     0.517540    0.502250    0.494707    0.483099    0.445870
std      0.291124    0.296978    0.303481    0.287126    0.283565
min      0.001114    0.003369    0.002270    0.001436    0.010423
25%      0.255693    0.236796    0.208453    0.230869    0.197932
50%      0.544396    0.506599    0.492189    0.482893    0.423202
75%      0.773076    0.766522    0.766298    0.717466    0.696868
max      0.999892    0.998330    0.998176    0.994617    0.995532

In [49]:
newDf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [50]:
newDf[0][0]= "Maaz Khan"

C:\Users\Muhammad Mubien\AppData\Local\Temp\ipykernel_2744\4095004716.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Maaz Khan' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newDf[0][0]= "Maaz Khan"

In [51]:
newDf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [52]:
newDf

             0         1         2         3         4
0    Maaz Khan  0.577195  0.100032  0.632805  0.258135
1     0.716267  0.861450  0.982896  0.193007  0.908535
2     0.515366  0.942627  0.583046  0.299769  0.535384
3     0.175034  0.030987  0.642900  0.135789  0.606995
4     0.439564  0.023421  0.172769  0.969795  0.147122
..         ...       ...       ...       ...       ...
325    0.28424  0.336885  0.539418  0.405030  0.883733
326   0.537784  0.311931  0.704493  0.643169  0.119080
327   0.931486  0.743379  0.156919  0.945241  0.419434
328   0.286289  0.351732  0.458231  0.810107  0.389686
329   0.678228  0.167879  0.798366  0.369167  0.867209

[330 rows x 5 columns]

In [53]:
newDf.index

RangeIndex(start=0, stop=330, step=1)

In [54]:
newDf.columns

RangeIndex(start=0, stop=5, step=1)

In [55]:
newDf.to_numpy()

array([['Maaz Khan', 0.5771950705444494, 0.10003192215932877,
        0.6328050914944447, 0.25813459215503654],
       [0.7162668200928615, 0.8614504958425001, 0.9828959741338997,
        0.19300695855731542, 0.9085349556520008],
       [0.5153659323209405, 0.9426268911177826, 0.5830459793771477,
        0.2997685574678113, 0.5353840039810247],
       ...,
       [0.9314857404478135, 0.743378865701031, 0.15691934117815454,
        0.9452409014713773, 0.41943364998052457],
       [0.28628915927928633, 0.3517323590943592, 0.45823062848206275,
        0.8101065091538399, 0.38968605034068815],
       [0.6782277793018667, 0.16787924248753627, 0.7983659775499196,
        0.3691674946313801, 0.8672085898277894]],
      shape=(330, 5), dtype=object)

In [56]:
newDf[0][0]=0.30

In [57]:
newDf.head()

          0         1         2         3         4
0       0.3  0.577195  0.100032  0.632805  0.258135
1  0.716267  0.861450  0.982896  0.193007  0.908535
2  0.515366  0.942627  0.583046  0.299769  0.535384
3  0.175034  0.030987  0.642900  0.135789  0.606995
4  0.439564  0.023421  0.172769  0.969795  0.147122

In [58]:
newDf.T

,0,1,2,3,4,5,6,7,8,9,...,320,321,322,323,324,325,326,327,328,329
0,0.3,0.716267,0.515366,0.175034,0.439564,0.89861,0.30542,0.471726,0.900466,0.294357,...,0.219481,0.566904,0.928741,0.980019,0.044,0.28424,0.537784,0.931486,0.286289,0.678228
1,0.577195,0.86145,0.942627,0.030987,0.023421,0.932452,0.100607,0.200705,0.302166,0.327811,...,0.451116,0.343285,0.363464,0.973968,0.819367,0.336885,0.311931,0.743379,0.351732,0.167879
2,0.100032,0.982896,0.583046,0.6429,0.172769,0.46582,0.096158,0.024803,0.394936,0.684081,...,0.424058,0.616424,0.384204,0.902675,0.483176,0.539418,0.704493,0.156919,0.458231,0.798366
3,0.632805,0.193007,0.299769,0.135789,0.969795,0.512325,0.568465,0.50851,0.013534,0.170785,...,0.109649,0.966909,0.214294,0.761166,0.239031,0.40503,0.643169,0.945241,0.810107,0.369167
4,0.258135,0.908535,0.535384,0.606995,0.147122,0.443754,0.054129,0.073589,0.349802,0.700499,...,0.532625,0.883878,0.559337,0.185638,0.255062,0.883733,0.11908,0.419434,0.389686,0.867209

In [59]:
newDf.sort_index(axis=0)

            0         1         2         3         4
0         0.3  0.577195  0.100032  0.632805  0.258135
1    0.716267  0.861450  0.982896  0.193007  0.908535
2    0.515366  0.942627  0.583046  0.299769  0.535384
3    0.175034  0.030987  0.642900  0.135789  0.606995
4    0.439564  0.023421  0.172769  0.969795  0.147122
..        ...       ...       ...       ...       ...
325   0.28424  0.336885  0.539418  0.405030  0.883733
326  0.537784  0.311931  0.704493  0.643169  0.119080
327  0.931486  0.743379  0.156919  0.945241  0.419434
328  0.286289  0.351732  0.458231  0.810107  0.389686
329  0.678228  0.167879  0.798366  0.369167  0.867209

[330 rows x 5 columns]

In [60]:
newDf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
329  0.678228  0.167879  0.798366  0.369167  0.867209
328  0.286289  0.351732  0.458231  0.810107  0.389686
327  0.931486  0.743379  0.156919  0.945241  0.419434
326  0.537784  0.311931  0.704493  0.643169  0.119080
325   0.28424  0.336885  0.539418  0.405030  0.883733
..        ...       ...       ...       ...       ...
4    0.439564  0.023421  0.172769  0.969795  0.147122
3    0.175034  0.030987  0.642900  0.135789  0.606995
2    0.515366  0.942627  0.583046  0.299769  0.535384
1    0.716267  0.861450  0.982896  0.193007  0.908535
0         0.3  0.577195  0.100032  0.632805  0.258135

[330 rows x 5 columns]

In [61]:
newDf.sort_index(axis=1)

            0         1         2         3         4
0         0.3  0.577195  0.100032  0.632805  0.258135
1    0.716267  0.861450  0.982896  0.193007  0.908535
2    0.515366  0.942627  0.583046  0.299769  0.535384
3    0.175034  0.030987  0.642900  0.135789  0.606995
4    0.439564  0.023421  0.172769  0.969795  0.147122
..        ...       ...       ...       ...       ...
325   0.28424  0.336885  0.539418  0.405030  0.883733
326  0.537784  0.311931  0.704493  0.643169  0.119080
327  0.931486  0.743379  0.156919  0.945241  0.419434
328  0.286289  0.351732  0.458231  0.810107  0.389686
329  0.678228  0.167879  0.798366  0.369167  0.867209

[330 rows x 5 columns]

In [62]:
newDf.sort_index(axis=1, ascending=False)

            4         3         2         1         0
0    0.258135  0.632805  0.100032  0.577195       0.3
1    0.908535  0.193007  0.982896  0.861450  0.716267
2    0.535384  0.299769  0.583046  0.942627  0.515366
3    0.606995  0.135789  0.642900  0.030987  0.175034
4    0.147122  0.969795  0.172769  0.023421  0.439564
..        ...       ...       ...       ...       ...
325  0.883733  0.405030  0.539418  0.336885   0.28424
326  0.119080  0.643169  0.704493  0.311931  0.537784
327  0.419434  0.945241  0.156919  0.743379  0.931486
328  0.389686  0.810107  0.458231  0.351732  0.286289
329  0.867209  0.369167  0.798366  0.167879  0.678228

[330 rows x 5 columns]

In [63]:
newDf.head()

          0         1         2         3         4
0       0.3  0.577195  0.100032  0.632805  0.258135
1  0.716267  0.861450  0.982896  0.193007  0.908535
2  0.515366  0.942627  0.583046  0.299769  0.535384
3  0.175034  0.030987  0.642900  0.135789  0.606995
4  0.439564  0.023421  0.172769  0.969795  0.147122

In [64]:
newDf[0][1]

0.7162668200928615

In [65]:
type(newDf[0])

pandas.core.series.Series

In [66]:
newDf

            0         1         2         3         4
0         0.3  0.577195  0.100032  0.632805  0.258135
1    0.716267  0.861450  0.982896  0.193007  0.908535
2    0.515366  0.942627  0.583046  0.299769  0.535384
3    0.175034  0.030987  0.642900  0.135789  0.606995
4    0.439564  0.023421  0.172769  0.969795  0.147122
..        ...       ...       ...       ...       ...
325   0.28424  0.336885  0.539418  0.405030  0.883733
326  0.537784  0.311931  0.704493  0.643169  0.119080
327  0.931486  0.743379  0.156919  0.945241  0.419434
328  0.286289  0.351732  0.458231  0.810107  0.389686
329  0.678228  0.167879  0.798366  0.369167  0.867209

[330 rows x 5 columns]

## view

In [67]:
newDfView=newDf

In [68]:
newDfView

            0         1         2         3         4
0         0.3  0.577195  0.100032  0.632805  0.258135
1    0.716267  0.861450  0.982896  0.193007  0.908535
2    0.515366  0.942627  0.583046  0.299769  0.535384
3    0.175034  0.030987  0.642900  0.135789  0.606995
4    0.439564  0.023421  0.172769  0.969795  0.147122
..        ...       ...       ...       ...       ...
325   0.28424  0.336885  0.539418  0.405030  0.883733
326  0.537784  0.311931  0.704493  0.643169  0.119080
327  0.931486  0.743379  0.156919  0.945241  0.419434
328  0.286289  0.351732  0.458231  0.810107  0.389686
329  0.678228  0.167879  0.798366  0.369167  0.867209

[330 rows x 5 columns]

In [69]:
newDfView[0][0]=765

C:\Users\Muhammad Mubien\AppData\Local\Temp\ipykernel_2744\4063526219.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newDfView[0][0]=765

In [70]:
newDf.head()

          0         1         2         3         4
0       765  0.577195  0.100032  0.632805  0.258135
1  0.716267  0.861450  0.982896  0.193007  0.908535
2  0.515366  0.942627  0.583046  0.299769  0.535384
3  0.175034  0.030987  0.642900  0.135789  0.606995
4  0.439564  0.023421  0.172769  0.969795  0.147122

In [123]:
newDfView.head()

          0         1         2         3         4
0       765  0.992326  0.029421  0.405688  0.591369
1  0.472891  0.937942  0.159810  0.810685  0.054391
2  0.152944  0.616511  0.396288  0.438617  0.898269
3  0.165207  0.528965  0.438421  0.608056  0.621835
4  0.929314  0.993836  0.748688  0.414415  0.318291

In [124]:
newDfCopy=newDf.copy()

In [125]:
newDfCopy[0][0]=656

C:\Users\HP\AppData\Local\Temp\ipykernel_10892\2532441962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newDfCopy[0][0]=656

In [126]:
newDf.head()

          0         1         2         3         4
0       765  0.992326  0.029421  0.405688  0.591369
1  0.472891  0.937942  0.159810  0.810685  0.054391
2  0.152944  0.616511  0.396288  0.438617  0.898269
3  0.165207  0.528965  0.438421  0.608056  0.621835
4  0.929314  0.993836  0.748688  0.414415  0.318291

In [127]:
newDfCopy.head()

          0         1         2         3         4
0       656  0.992326  0.029421  0.405688  0.591369
1  0.472891  0.937942  0.159810  0.810685  0.054391
2  0.152944  0.616511  0.396288  0.438617  0.898269
3  0.165207  0.528965  0.438421  0.608056  0.621835
4  0.929314  0.993836  0.748688  0.414415  0.318291

## loc

In [128]:
newDf.head(2)

          0         1         2         3         4
0       765  0.992326  0.029421  0.405688  0.591369
1  0.472891  0.937942  0.159810  0.810685  0.054391

In [129]:
newDf.loc[0,0]

765

In [130]:
newDf.loc[0,0]=5678

In [131]:
newDf.head(2)

          0         1         2         3         4
0      5678  0.992326  0.029421  0.405688  0.591369
1  0.472891  0.937942  0.159810  0.810685  0.054391

In [132]:
newDf.loc[0,4]

0.5913694342372785

In [133]:
newDf.loc[325,1]

0.17087730222900788

In [134]:
newDf.loc[0,0]=9875

In [135]:
newDf.head(2)

          0         1         2         3         4
0      9875  0.992326  0.029421  0.405688  0.591369
1  0.472891  0.937942  0.159810  0.810685  0.054391

In [136]:
newDf.columns=list("ABCDE")

In [137]:
newDf.head(3)

          A         B         C         D         E
0      9875  0.992326  0.029421  0.405688  0.591369
1  0.472891  0.937942  0.159810  0.810685  0.054391
2  0.152944  0.616511  0.396288  0.438617  0.898269

In [138]:
newDf.loc[0, "A"]

9875

In [139]:
newDf.loc[0,"A"]=65

In [140]:
newDf.head(3)

          A         B         C         D         E
0        65  0.992326  0.029421  0.405688  0.591369
1  0.472891  0.937942  0.159810  0.810685  0.054391
2  0.152944  0.616511  0.396288  0.438617  0.898269

In [141]:
newDf.loc[35,"A"]

0.34404651840383504

In [142]:
newDf.drop(0, axis=0).head(3)

          A         B         C         D         E
1  0.472891  0.937942  0.159810  0.810685  0.054391
2  0.152944  0.616511  0.396288  0.438617  0.898269
3  0.165207  0.528965  0.438421  0.608056  0.621835

In [143]:
newDf.drop("A", axis=1).head(3)

          B         C         D         E
0  0.992326  0.029421  0.405688  0.591369
1  0.937942  0.159810  0.810685  0.054391
2  0.616511  0.396288  0.438617  0.898269

In [144]:
newDf.head(3)

          A         B         C         D         E
0        65  0.992326  0.029421  0.405688  0.591369
1  0.472891  0.937942  0.159810  0.810685  0.054391
2  0.152944  0.616511  0.396288  0.438617  0.898269

In [145]:
newDf = newDf.drop("A", axis=1)

In [146]:
newDf.head(3)

          B         C         D         E
0  0.992326  0.029421  0.405688  0.591369
1  0.937942  0.159810  0.810685  0.054391
2  0.616511  0.396288  0.438617  0.898269

In [147]:
newDf.loc[[1,2],["C","D"]]

          C         D
1  0.159810  0.810685
2  0.396288  0.438617

In [148]:
newDf.head(3)

          B         C         D         E
0  0.992326  0.029421  0.405688  0.591369
1  0.937942  0.159810  0.810685  0.054391
2  0.616511  0.396288  0.438617  0.898269

In [149]:
newDf.loc[:,["C","D"]]

            C         D
0    0.029421  0.405688
1    0.159810  0.810685
2    0.396288  0.438617
3    0.438421  0.608056
4    0.748688  0.414415
..        ...       ...
325  0.510583  0.102239
326  0.922017  0.109421
327  0.872122  0.080016
328  0.886492  0.942696
329  0.133443  0.873607

[330 rows x 2 columns]

In [150]:
newDf.loc[[1,2],:]

          B         C         D         E
1  0.937942  0.159810  0.810685  0.054391
2  0.616511  0.396288  0.438617  0.898269

In [151]:
newDf.loc[:5,["C","D"]]

          C         D
0  0.029421  0.405688
1  0.159810  0.810685
2  0.396288  0.438617
3  0.438421  0.608056
4  0.748688  0.414415
5  0.585854  0.375922

In [152]:
newDf.loc[[1,2],:"D"]

          B         C         D
1  0.937942  0.159810  0.810685
2  0.616511  0.396288  0.438617

In [153]:
newDf.loc[(newDf["B"]<0.3)]

            B         C         D         E
5    0.226901  0.585854  0.375922  0.855481
6    0.298088  0.808357  0.612956  0.292066
7    0.185523  0.776844  0.625154  0.281869
8    0.103625  0.185792  0.370414  0.289675
9    0.101683  0.787454  0.005102  0.871137
..        ...       ...       ...       ...
315  0.222196  0.743926  0.424952  0.257754
321  0.163032  0.590114  0.022772  0.620229
324  0.017750  0.819989  0.418852  0.466498
325  0.170877  0.510583  0.102239  0.375501
329  0.098887  0.133443  0.873607  0.342575

[106 rows x 4 columns]

In [154]:
newDf.loc[(newDf["B"]<0.3) & (newDf["D"]>0.2)]

            B         C         D         E
5    0.226901  0.585854  0.375922  0.855481
6    0.298088  0.808357  0.612956  0.292066
7    0.185523  0.776844  0.625154  0.281869
8    0.103625  0.185792  0.370414  0.289675
10   0.286224  0.167519  0.629715  0.656681
..        ...       ...       ...       ...
312  0.190419  0.790646  0.507998  0.751695
313  0.118357  0.291732  0.465498  0.652851
315  0.222196  0.743926  0.424952  0.257754
324  0.017750  0.819989  0.418852  0.466498
329  0.098887  0.133443  0.873607  0.342575

[79 rows x 4 columns]

In [155]:
newDf.head(3)

          B         C         D         E
0  0.992326  0.029421  0.405688  0.591369
1  0.937942  0.159810  0.810685  0.054391
2  0.616511  0.396288  0.438617  0.898269

## iloc

In [156]:
newDf.iloc[0,0]

0.992325669505626

In [157]:
newDf.iloc[0,0]=555

In [158]:
newDf.head()

            B         C         D         E
0  555.000000  0.029421  0.405688  0.591369
1    0.937942  0.159810  0.810685  0.054391
2    0.616511  0.396288  0.438617  0.898269
3    0.528965  0.438421  0.608056  0.621835
4    0.993836  0.748688  0.414415  0.318291

In [159]:
newDf.iloc[[0,4],[1,3]]

          C         E
0  0.029421  0.591369
4  0.748688  0.318291

In [160]:
newDf.head(4)

            B         C         D         E
0  555.000000  0.029421  0.405688  0.591369
1    0.937942  0.159810  0.810685  0.054391
2    0.616511  0.396288  0.438617  0.898269
3    0.528965  0.438421  0.608056  0.621835

In [161]:
newDf.drop(0).head()

          B         C         D         E
1  0.937942  0.159810  0.810685  0.054391
2  0.616511  0.396288  0.438617  0.898269
3  0.528965  0.438421  0.608056  0.621835
4  0.993836  0.748688  0.414415  0.318291
5  0.226901  0.585854  0.375922  0.855481

In [162]:
# newDf.drop(0, axis=1)

In [163]:
# newDf.drop("B", axis=1).head()

In [164]:
newDf.drop(["C", "D"], axis=1).head()

            B         E
0  555.000000  0.591369
1    0.937942  0.054391
2    0.616511  0.898269
3    0.528965  0.621835
4    0.993836  0.318291

In [165]:
newDf.head()

            B         C         D         E
0  555.000000  0.029421  0.405688  0.591369
1    0.937942  0.159810  0.810685  0.054391
2    0.616511  0.396288  0.438617  0.898269
3    0.528965  0.438421  0.608056  0.621835
4    0.993836  0.748688  0.414415  0.318291

In [166]:
newDf.drop(['B', 'D'], axis=1, inplace=True)

In [167]:
newDf.head()

          C         E
0  0.029421  0.591369
1  0.159810  0.054391
2  0.396288  0.898269
3  0.438421  0.621835
4  0.748688  0.318291

In [168]:
newDf.reset_index().head()

   index         C         E
0      0  0.029421  0.591369
1      1  0.159810  0.054391
2      2  0.396288  0.898269
3      3  0.438421  0.621835
4      4  0.748688  0.318291

In [163]:
newDf.reset_index(drop=True).head()

          C         E
0  0.870811  0.034058
1  0.209813  0.851167
2  0.781053  0.239450
3  0.940346  0.008776
4  0.409709  0.279607

In [164]:
newDf.head()

          C         E
0  0.870811  0.034058
1  0.209813  0.851167
2  0.781053  0.239450
3  0.940346  0.008776
4  0.409709  0.279607

In [167]:
newDf.reset_index(drop=True, inplace=True)

In [168]:
newDf.head()

          C         E
0  0.870811  0.034058
1  0.209813  0.851167
2  0.781053  0.239450
3  0.940346  0.008776
4  0.409709  0.279607

# Groupby
The groupby method allows you to group rows of data together and call aggregate functions

​
​

In [2]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [15]:
df = pd.DataFrame(data)

In [16]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

### Now you can use the .groupby() method to group rows together based off of a column name.
For instance let's group based off of Company. This will create a DataFrameGroupBy object:

In [6]:
df.groupby('Company')

##### You can save this object as a new variable:

In [7]:
by_comp = df.groupby("Company")
type(by_comp)

pandas.core.groupby.generic.DataFrameGroupBy

#### And then call aggregate methods of the object:

In [8]:
by_comp.mean()

C:\Users\HP\AppData\Local\Temp\ipykernel_960\821838057.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  by_comp.mean()

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [9]:
df.groupby('Company').mean()

C:\Users\HP\AppData\Local\Temp\ipykernel_960\2058252646.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Company').mean()

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [10]:
by_comp.std()

C:\Users\HP\AppData\Local\Temp\ipykernel_960\3391457442.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  by_comp.std()

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [11]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [12]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [13]:
by_comp.count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [14]:
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0